In [49]:
from tensorflow.keras.preprocessing.text import one_hot


In [50]:
sentences = [
    'I love programming in Python',
    'Python is a great programming language',
    'I enjoy learning new programming languages',
    'Machine learning is fascinating',
    'Deep learning is a subset of machine learning'

]

In [51]:
# Define the vocabulary size
vocubalary_size = 10000

In [52]:
# One hot representation of the sentences
one_hot_representations = [one_hot(words, vocubalary_size) for words in sentences]
one_hot_representations

[[2376, 7910, 4650, 1781, 3720],
 [3720, 7579, 6844, 5524, 4650, 3614],
 [2376, 7100, 8337, 2032, 4650, 3357],
 [1665, 8337, 7579, 8573],
 [3783, 8337, 7579, 6844, 6223, 4694, 1665, 8337]]

In [53]:
# Word Embedding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import pad_sequences

from tensorflow.keras.models import Sequential


In [54]:
import numpy as np  

In [55]:
max_sentence_length = 10
embedded_docs = pad_sequences(one_hot_representations, maxlen=max_sentence_length, padding='pre')
print(embedded_docs)

[[   0    0    0    0    0 2376 7910 4650 1781 3720]
 [   0    0    0    0 3720 7579 6844 5524 4650 3614]
 [   0    0    0    0 2376 7100 8337 2032 4650 3357]
 [   0    0    0    0    0    0 1665 8337 7579 8573]
 [   0    0 3783 8337 7579 6844 6223 4694 1665 8337]]


In [56]:
# Feature representation 
dimension = 10

In [59]:
model = Sequential()
model.add(Embedding(vocubalary_size, dimension, input_length=max_sentence_length))
model.build(input_shape=(None, max_sentence_length))
model.compile('adam', 'mse')

/Users/user/Developer/Gen-AI/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [60]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [61]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step


array([[[-0.04580592, -0.01836947, -0.02711217,  0.01211516,
         -0.02384237,  0.00751432, -0.01294097, -0.04012871,
         -0.02103598,  0.04498592],
        [-0.04580592, -0.01836947, -0.02711217,  0.01211516,
         -0.02384237,  0.00751432, -0.01294097, -0.04012871,
         -0.02103598,  0.04498592],
        [-0.04580592, -0.01836947, -0.02711217,  0.01211516,
         -0.02384237,  0.00751432, -0.01294097, -0.04012871,
         -0.02103598,  0.04498592],
        [-0.04580592, -0.01836947, -0.02711217,  0.01211516,
         -0.02384237,  0.00751432, -0.01294097, -0.04012871,
         -0.02103598,  0.04498592],
        [-0.04580592, -0.01836947, -0.02711217,  0.01211516,
         -0.02384237,  0.00751432, -0.01294097, -0.04012871,
         -0.02103598,  0.04498592],
        [ 0.02569294, -0.01369404, -0.00613201, -0.04568034,
         -0.00659353, -0.03977481,  0.01896423,  0.01676898,
          0.04387534, -0.02519676],
        [ 0.02897977,  0.03990242, -0.04222404,  0.0

In [ ]:
class Solution:
    def lengthOfLongestSubstring(self, s: str) -> int:
        n = set()
        for char in s:
            # print(char)

            if char not in n:
                n.add(char)
            else:
                len_s = len(n)
                for i in range(len_s):
                    n.remove(s[i])
                
                print(len(n))
                print(f"{char}, available set values: {n}")

        print(n)
        return len(n)
    
sn = Solution()
ans = sn.lengthOfLongestSubstring("pwwkew")
print(ans)

KeyError: 0